# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s15ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/zyhwork/Lab_9/Lab_9.cache/wt [current_project]
set_property parent.project_path D:/zyhwork/Lab_9/Lab_9.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/zyhwork/Frequency_Divider_Demo/Frequency_Divider_Demo.srcs/xgui
  d:/zyhwork/Frequency_Divider_Demo
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/zyhwork/Lab_9/Lab_9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files e:/matlab/matlab_all/bin/Triangle_Wave_Rom.coe
add_files e:/matlab/matlab_all/bin/Square_Wave_Rom.coe
add_files e:/matlab/matlab_all/bin/Sin_Wave_Rom.coe
read_verilog -library xil_defaultlib {
  D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/new/DDS_Addr_Generator.v
  D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/new/Driver_DAC.v
  D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/new/Lab_9.v
}
read_ip -quiet D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/clk_division_0/clk_division_0.xci

read_ip -quiet D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle.xci
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Triangle/Rom_Triangle_ooc.xdc]

read_ip -quiet D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Square/Rom_Square.xci
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Square/Rom_Square_ooc.xdc]

read_ip -quiet D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Sin/Rom_Sin.xci
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/Rom_Sin/Rom_Sin_ooc.xdc]

read_ip -quiet D:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/clk_5_10/clk_5_10.xci
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/clk_5_10/clk_5_10_board.xdc]
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/clk_5_10/clk_5_10.xdc]
set_property used_in_implementation false [get_files -all d:/zyhwork/Lab_9/Lab_9.srcs/sources_1/ip/clk_5_10/clk_5_10_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Lab_9 -part xc7s15ftgb196-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab_9.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab_9_utilization_synth.rpt -pb Lab_9_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
